#include "../header.h"
void print(li*, int);
li mod(li, li);
li mcd(li, li);
li* cribaEratostenes(li, li*);
li* primeNext(li, li, li*);
li* factorizacion(li, li*);
li* option(li, li, li, li*);
li randomOdd(li);
li randomp(li);
int op(li, li, li);
li* bezout(li, li);
void euclidesExtendido(li, li);
li* inverso(li, li);
li* gordon(li, li);
li* exponenciacion(li, li, li*, int);
bool isStrongPrime(li, li, li);
li previousPrime(li);
li* generadores(li, li, li*, li (*)(li, li*, li));
li repetido(li, li*, li);
li* legendre(li, li);
